"""Interactive wizard for `wally init` — scaffolds wally.toml.

Presents a pre-selected checkbox list of categories (questionary), collects a
monthly limit for each chosen category, and writes wally.toml. Aborts
non-destructively if the file already exists and the user declines to overwrite.
"""

from __future__ import annotations

from decimal import Decimal, InvalidOperation
from pathlib import Path

import questionary
from rich.console import Console
from rich.prompt import Confirm, Prompt

# Ordered default categories. Key becomes the TOML key; label is displayed.
CATEGORIES: list[tuple[str, str]] = [
    ("groceries", "Groceries"),
    ("restaurants", "Restaurants"),
    ("transportation", "Transportation"),
    ("entertainment", "Entertainment"),
    ("shopping", "Shopping"),
    ("personal_care", "Personal Care"),
    ("home_and_garden", "Home & Garden"),
    ("travel", "Travel"),
    ("utilities", "Utilities"),
    ("services", "Services"),
]


def _select_categories() -> list[tuple[str, str]] | None:
    """Checkbox multiselect — all pre-selected. Returns None if the user cancels."""
    choices = [
        questionary.Choice(label, value=(key, label), checked=True) for key, label in CATEGORIES
    ]
    result = questionary.checkbox(
        "Select budget categories",
        choices=choices,
        instruction="(space to toggle, enter to confirm)",
    ).ask()
    return result  # list of (key, label) tuples, or None on Ctrl-C


def prompt_limit(label: str, console: Console) -> Decimal:
    """Prompt until the user enters a valid positive decimal."""
    while True:
        raw = Prompt.ask(f"  Monthly limit for [bold]{label}[/bold]")
        try:
            value = Decimal(raw.strip().lstrip("$").replace(",", ""))
            if value > 0:
                return value
        except InvalidOperation:
            pass
        console.print("  [red]Enter a positive number (e.g. 250 or 250.00)[/red]")


def build_toml(limits: dict[str, Decimal]) -> str:
    """Render wally.toml content from a key→Decimal mapping."""
    lines = [
        "# Wally budget config — generated by `wally init`.",
        "# Amounts are quoted strings to preserve exact decimal values.",
        "",
        "[budget.limits]",
    ]
    for key, amount in limits.items():
        lines.append(f'{key} = "{amount:.2f}"')
    return "\n".join(lines) + "\n"


def run_init(config_path: str, console: Console | None = None) -> int:
    """Run the interactive init wizard. Returns a process exit code."""
    if console is None:
        console = Console()

    path = Path(config_path)
    if path.exists():
        overwrite = Confirm.ask(
            f"[yellow]{path}[/yellow] already exists. Overwrite?", default=False
        )
        if not overwrite:
            console.print("Aborted — existing config unchanged.")
            return 1

    console.print()
    selected = _select_categories()

    if selected is None:
        console.print("\nAborted.")
        return 1
    if not selected:
        console.print("[yellow]No categories selected — nothing written.[/yellow]")
        return 1

    console.print()
    limits: dict[str, Decimal] = {}
    for key, label in selected:
        limits[key] = prompt_limit(label, console)

    path.write_text(build_toml(limits))
    console.print(f"\n[green]✓[/green] Written to [bold]{path}[/bold]\n")
    console.print("Run [bold]wally[/bold] to generate your first report.")
    return 0
