"""Interactive wizard for `wally init` — scaffolds wally.toml.

Presents a numbered category list, collects monthly limits for the chosen
categories, and writes a wally.toml. Aborts (non-destructively) if the file
already exists and the user declines to overwrite.
"""

from __future__ import annotations

from decimal import Decimal, InvalidOperation
from pathlib import Path

from rich.console import Console
from rich.prompt import Confirm, Prompt
from rich.table import Table

# Ordered default categories. Key is the TOML key; label is the display name.
CATEGORIES: list[tuple[str, str]] = [
    ("groceries", "Groceries"),
    ("restaurants", "Restaurants"),
    ("transportation", "Transportation"),
    ("entertainment", "Entertainment"),
    ("shopping", "Shopping"),
    ("personal_care", "Personal Care"),
    ("home_and_garden", "Home & Garden"),
    ("travel", "Travel"),
    ("utilities", "Utilities"),
    ("services", "Services"),
]


def _show_category_menu(console: Console) -> None:
    table = Table(box=None, show_header=False, pad_edge=False)
    table.add_column(justify="right", style="dim")
    table.add_column()
    for i, (_, label) in enumerate(CATEGORIES, 1):
        table.add_row(str(i), label)
    console.print(table)


def parse_selection(raw: str, total: int) -> list[int] | None:
    """Parse a comma-separated number string into 0-based indices.

    Returns None if any token is invalid or out of range.
    """
    raw = raw.strip().lower()
    if raw == "all":
        return list(range(total))
    indices = []
    for token in raw.split(","):
        token = token.strip()
        if not token.isdigit():
            return None
        n = int(token)
        if n < 1 or n > total:
            return None
        indices.append(n - 1)
    return indices if indices else None


def prompt_limit(label: str, console: Console) -> Decimal:
    """Prompt until the user enters a valid positive decimal."""
    while True:
        raw = Prompt.ask(f"  Monthly limit for [bold]{label}[/bold]")
        try:
            value = Decimal(raw.strip().lstrip("$").replace(",", ""))
            if value > 0:
                return value
        except InvalidOperation:
            pass
        console.print("  [red]Enter a positive number (e.g. 250 or 250.00)[/red]")


def build_toml(limits: dict[str, Decimal]) -> str:
    """Render the wally.toml content string from a key→Decimal mapping."""
    lines = [
        "# Wally budget config — generated by `wally init`.",
        "# Amounts are quoted strings to preserve exact decimal values.",
        "",
        "[budget.limits]",
    ]
    for key, amount in limits.items():
        lines.append(f'{key} = "{amount:.2f}"')
    return "\n".join(lines) + "\n"


def run_init(config_path: str, console: Console | None = None) -> int:
    """Run the interactive init wizard. Returns a process exit code."""
    if console is None:
        console = Console()

    path = Path(config_path)
    if path.exists():
        overwrite = Confirm.ask(
            f"[yellow]{path}[/yellow] already exists. Overwrite?", default=False
        )
        if not overwrite:
            console.print("Aborted — existing config unchanged.")
            return 1

    console.print("\n[bold]Select budget categories[/bold] (you can add more later)\n")
    _show_category_menu(console)
    console.print()

    while True:
        raw = Prompt.ask('Enter numbers to include (e.g. [dim]1,3,5[/dim]) or [dim]"all"[/dim]')
        indices = parse_selection(raw, len(CATEGORIES))
        if indices is not None:
            break
        console.print('[red]Invalid selection — enter comma-separated numbers or "all"[/red]')

    selected = [CATEGORIES[i] for i in indices]
    console.print()

    limits: dict[str, Decimal] = {}
    for key, label in selected:
        limits[key] = prompt_limit(label, console)

    path.write_text(build_toml(limits))
    console.print(f"\n[green]✓[/green] Written to [bold]{path}[/bold]\n")
    console.print("Run [bold]wally[/bold] to generate your first report.")
    return 0
